os: linux
dist: focal
language: minimal
before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential qemu-user-static xz-utils gnupg wget binfmt-support
install:
  - if ! [ -d /proc/sys/fs/binfmt_misc ]; then sudo modprobe binfmt_misc; fi
  - if ! [ -f /proc/sys/fs/binfmt_misc/register ]; then sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/qemu-wrapper:' | sudo tee /proc/sys/fs/binfmt_misc/register
  - sudo /etc/init.d/binfmt-support start
before_script:
  - wget https://toolchains.bootlin.com/downloads/releases/toolchains/armv6-eabihf/tarballs/armv6-eabihf--glibc--bleeding-edge-2020.08-1.tar.bz2
  - tar xf armv6-eabihf--glibc--bleeding-edge-2020.08-1.tar.bz2
  - export PATH=$PATH:$PWD/armv6-eabihf--glibc--bleeding-edge-2020.08-1/bin
script:
  - make -j$(nproc) -e QEMU_ARM=/usr/bin/qemu-arm-static CROSS_COMPILE=arm-buildroot-linux-gnueabihf- image
